# FROM ubuntu:focal

# RUN apt-get update && apt-get install -y locales && rm -rf /var/lib/apt/lists/* \
#   && localedef -i en_US -c -f UTF-8 -A /usr/share/locale/locale.alias en_US.UTF-8
# ENV LANG en_US.utf8
# https://github.com/Docker-Hub-frolvlad/docker-alpine-python3/blob/master/Dockerfile
FROM node:16-alpine3.12

ENV PYTHONUNBUFFERED=1

RUN echo "**** install Python ****" && \
    apk add --no-cache python3 && \
    if [ ! -e /usr/bin/python ]; then ln -sf python3 /usr/bin/python ; fi && \
    \
    echo "**** install pip ****" && \
    python3 -m ensurepip && \
    rm -r /usr/lib/python*/ensurepip && \
    pip3 install --no-cache --upgrade pip setuptools wheel && \
    if [ ! -e /usr/bin/pip ]; then ln -s pip3 /usr/bin/pip ; fi

RUN pip3 install video-to-ascii opencv-python